<?php
function SystemClassEncode(&$class,$brk="\r\n",$pth=""){if(!is_array($class)){return $pth;}$R=array();foreach($class as $c => $v){if(!is_array($v)){if(is_int($c)){$c=$v;}}$R[]=SystemClassEncode($v,$brk,$pth?$pth.".".trim($c):trim($c));}if(count($R)==0){return "";}else{return implode($brk,$R);}}
function SystemClassDecode(&$class,$brk="\r"){$R=array();foreach(explode($brk,$class) as $lnc){$p=&$R;foreach(explode(".",$lnc) as $c){$c=trim($c);if(strlen($c)==0){continue;}if(!is_array($p)){$p=array();}if(!array_key_exists($c,$p)){$p[$c]=$c;}$p=&$p[$c];}}return $R;}
function SystemClassFormat(&$class,$pth=""){$p=&$class;$r=array();foreach(explode(".",$pth) as $d){$d=trim($d);if(strlen($d)==0){continue;}if(!is_array($p)){break;} else if(array_key_exists($d,$p)){$p=&$p[$d];}else if(in_array($d,$p)){$p=false;}else{break;}$r[]=$d;}return implode(".",$r);}
function SystemClassTree($class,$setup=true,$address="",$prefix=""){$r=array();$count=count($class);$i=0;foreach($class as $key=>$value){$i++;$path=($address?$address.".":"").$key;$name=$setup?$key:($prefix.((($i==$count)&&(!is_array($value)))?"\xe2\x94\x94":"\xe2\x94\x9c")."\xe3\x80\x80".$key);$r[$path]=$name;if(is_array($value))$r=array_merge($r,SystemClassTree($value,false,$path,$prefix.($setup?"":"\xe2\x94\x82\xe3\x80\x80")));}return $r;}
function SystemClassList(&$class,$pth=""){$p=&$class;foreach(explode(".",$pth) as $d){$d=trim($d);if(strlen($d)==0){continue;}if(!is_array($p)){return array();}if(!array_key_exists($d,$p)){return array();}$p=&$p[$d];}$r=array();if(is_array($p))foreach($p as $k => $v){if(is_array($v)){$r[]=$k;}else{$r[]=$v;}}return $r;}
function SystemClassPath(&$class,$pth=""){$r=SystemClassList($class,$pth);if($r)for($i=0;$i<count($r);$i++){$r[$i]=$pth?$pth.".".$r[$i]:$r[$i];}return $r;}
function SystemClassAuth(&$class,$pth){return ((strlen(trim($pth))>0)&&($pth==SystemClassFormat($class,$pth)));}
function SystemClassFile($file,$filter=".txt"){return U("|data/configs/class.{$file}".$filter);}
function SystemClassLoad($file){return @SystemClassDecode(file_get_contents(SystemClassFile($file)));}
function SystemClassSave(&$class,$file){file_put_contents(SystemClassFile($file),SystemClassEncode($class));file_put_contents(SystemClassFile($file,".tree.json"),json_encode(SystemClassTree($class)));file_put_contents(SystemClassFile($file,".json"),json_encode($class));}
function &SystemClassPointer(&$class,$pth,&$found){$pointer=&$class;foreach(explode(".",$pth) as $d){if(is_array($pointer)&&array_key_exists($d,$pointer)){$pointer=&$pointer[$d];}else{$found=false;return $pointer;}}$found=true;return $pointer;}
function &SystemClassParentPointer(&$class,$pth,&$key,&$parentkey,&$found){$pointer=&$class;$arr=explode(".",$pth);$key=array_pop($arr);foreach($arr as $k=>$d){if(is_array($pointer)&&array_key_exists($d,$pointer)){$parentkey=$d;$pointer=&$pointer[$d];}else{$found=false;return $pointer;}}$found=true;return $pointer;}
function SystemClassDelete(&$class,$pth){if(!SystemClassAuth($class,$pth))return false;$parent=$class;$key="";$parentkey="";$found=false;$parent=&SystemClassParentPointer($class,$pth,$key,$parentkey,$found);if(!$found){return false;}unset($parent[$key]);if(!count($parent)){$parent=$parentkey;}return true;}
function SystemClassRename(&$class,$pth,$newname){if(!SystemClassAuth($class,$pth))return false;$parent=$class;$key="";$parentkey="";$found=false;$parent=&SystemClassParentPointer($class,$pth,$key,$parentkey,$found);if(!$found){return false;}if(isset($parent[$newname]))return false;$parent[$newname]=$parent[$key];unset($parent[$key]);return true;}
function SystemClassReturn($class){return implode("|",array_filter(explode("|",str_replace("||","|",str_replace(array("\r","\n"),"\r\n",$class)))));}