<?php
function DB($SQL=null){static $DB;if(!$DB){$db=@parse_url(defined("DATABASE")?DATABASE:"");$db or $db=array();global $_DBTYPE;foreach(array("scheme","host","port","user","pass","path") as $k)$$k=isset($db[$k])?$db[$k]:null;$scheme=strtolower(trim($db["scheme"]));if($scheme=="mysql"){$_DBTYPE=$scheme;$path=trim($path,"/");$dsn="mysql:host=".($host?$host:"localhost").";port=".($port?$port:"3306").";dbname=".($path?$path:"test");}else{$host=$host?$host:"DSN";$dsn=defined($host)?constant($host):($host.".db");$dsn=strpos($dsn,":")?$dsn:("sqlite:".$dsn);$_DBTYPE=strtolower(trim(substr($dsn,0,strpos($dsn,":"))));}if($user && $pass){try{$DB=new PDO($dsn,$user,$pass);}catch(PDOException $E){die($E->getMessage());}}elseif($user){try{$DB=new PDO($dsn,$user);}catch(PDOException $E){die($E->getMessage());}}else{try{$DB=new PDO($dsn);}catch(PDOException $E){die($E->getMessage());}}try{$DB->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);}catch(PDOException $E){die($E->getMessage());}if($_DBTYPE=="mysql"){$DB->exec("SET NAMES 'UTF8'");$DB->exec("SET @@sql_mode=''");}}return $SQL?$DB->query($SQL):$DB;}
function Table($Table,$Data=array(),$Where=null,$Param=array()){$DB=DB();if(is_array($Data)){if(!count($Data))return 0;$stmt=$DB->prepare($Where?("UPDATE `{$Table}` SET `".implode("`=?,`",array_keys($Data))."`=? WHERE {$Where}"):("INSERT INTO `{$Table}` (`".implode("`,`",array_keys($Data))."`) VALUES (".implode(",",str_split(str_repeat("?",count($Data)))).")"));if(!$stmt)return 0;return $stmt->execute(is_array($Param)?array_merge(array_values($Data),$Param):array_values($Data))?($Where?$stmt->rowCount():$DB->lastInsertId()):0;}elseif($Where){$stmt=$DB->prepare("DELETE FROM `{$Table}` WHERE ".$Where);if(!$stmt)return 0;return is_array($Param)?($stmt->execute($Param)?$stmt->rowCount():0):($stmt->execute()?$stmt->rowCount():0);}else{return 0;}}
function Select($Field,$Table,$Expression=null,$Param=array()){$DB=DB();if(is_array($Field))$Field=implode(",",$Field);$stmt=$DB->prepare("SELECT {$Field} FROM `{$Table}` ".$Expression);if(!$stmt)return array();return (is_array($Param)?$stmt->execute($Param):$stmt->execute())?$stmt->fetchAll():array();}
function SelectCount($Table,$Expression=null,$Param=array()){$count=Select("COUNT(*)",$Table,$Expression,$Param);return $count?array_shift(array_shift($count)):0;}
function SelectPage($Table,$Page=1,$Count=30,$Order=null,$Where=null,$Param=array()){$Page=max(intval($Page),0);$Count=max(intval($Count),1);$Total=SelectCount($Table,$Where,$Param);$MaxPage=max(ceil($Total/$Count),1);$Page=max(min($Page,$MaxPage),1);$Pn=5;$pn=array_unique(array_merge(range(1,min($Pn,$MaxPage)),range(max($Page-floor($Pn/2),1),min($Page+floor($Pn/2),$MaxPage)),range(max(($MaxPage-$Pn+1),1),$MaxPage)));$PN=array("page"=>$Page,"count"=>$Count,"total"=>$Total,"maxpage"=>$MaxPage,"pn"=>$pn);if($Total<1)return array($PN);$Limit=($Page-1)*$Count.",".$Count;$Result=Select("*",$Table,($Where?"WHERE ".$Where." ":"").($Order?" ORDER BY ".$Order." ":"")."LIMIT ".$Limit,$Param);array_unshift($Result,$PN);return $Result;}
function CreateTable($Table,$Data=array()){$DB=DB();global $_DBTYPE;$Param=array();foreach($Data as $k=>$v){$v=strtoupper(trim($v));if($v=="ID"){switch($_DBTYPE){case "sqlite":$v="INTEGER";break;case "mssql":$v="BIGINT IDENTITY(1,1)";break;default:$v="BIGINT UNSIGNED AUTO_INCREMENT";}$v.=" PRIMARY KEY";}elseif(in_array($v,array("INT","LONGINT"))){$v="INTEGER";}elseif(in_array($v,array("SINGLE","FLOAT"))){$v="DOUBLE";}elseif($v=="BOOL"){$v="BOOLEAN";}elseif($v=="SHORTSTRING"){$v="VARCHAR(255)";}elseif($v=="STRING"){$v="TEXT";}elseif($v=="INT64"){$v="BIGINT";}elseif($v=="CARDINAL"){$v="INTEGER UNSIGNED";}elseif($v=="SHORTINT"){$v="TINYINT";}elseif($v=="BYTE"){$v="TINYINT UNSIGNED";}elseif($v=="WORD"){$v="SMALLINT UNSIGNED";}$Param[]=is_integer($k)?$v:"`{$k}` {$v}";}$Param="CREATE TABLE IF NOT EXISTS `{$Table}` (".implode(",",$Param).")";$DB->query($Param);}
function DropTable($Table){DB("DROP TABLE IF EXISTS `{$Table}`");}
function ResetTable($Table){DB("DELETE FROM `{$Table}`");global $_DBTYPE;if($_DBTYPE=="mysql")DB("ALTER TABLE `{$Table}` AUTO_INCREMENT=1");}
function ImportSQL($file,$pdo=false){$c=0;$f=@fopen($file,"r");if($f){$q="";while($line=fgets($f,1024000)){if(substr($line,0,2)=="--" OR trim($line)=="")continue;$q.=$line;if(substr(trim($q),-1)==";"){if($pdo){DB($q);}else{M($q);}$q="";$c++;}}fclose($f);}return $c;}